typography_spectrum: 0.5041956948116422
color:
  brandColors: []
  brandStrength: 0.25
  lightness: 0.29449973488226533
  saturation: 0.28817781736142933
  rhythmicContrast: 0.49027803470380604
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3866
analytics:
  google: null
  facebook: null
  twitter: null
name: NortonZanini
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
