name: NortonZanini
favicon: null
layout_spectrum: 0.3866
typography_spectrum: 0.5041956948116422
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.25
  lightness: 0.29449973488226533
  saturation: 0.28817781736142933
  rhythmicContrast: 0.49027803470380604
purpose: []
